name: Build and deploy Python project to Azure Function App - bookmarkgenie-functions

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**/function.json'
      - 'requirements.txt'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    env:
      FUNCTIONS_WORKER_RUNTIME: python
      SCM_DO_BUILD_DURING_DEPLOYMENT: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Force Python alias
        run: |
          sudo ln -sf $(which python3.10) /usr/bin/python
          sudo ln -sf $(which pip3.10) /usr/bin/pip

      - name: Force override Python globally
        run: |
          echo "python=$(which python3.10)" >> $GITHUB_ENV
          echo "/opt/hostedtoolcache/Python/3.10.13/x64/bin" >> $GITHUB_PATH
          which python
          python --version
          pip --version

      - name: Confirm enforced Python context
        run: |
          python --version
          pip --version
          which python
          which pip

      - name: Preinstall stable setuptools
        run: |
          python -m pip install setuptools==68.2.2

      - name: DEBUG – Dry-run pip resolution plan
        run: |
          python -m pip install --no-build-isolation --only-binary=:all: -r requirements.txt --dry-run -v

      - name: Install dependencies (no build isolation)
        run: |
          python -m pip install --prefer-binary --no-build-isolation --only-binary=:all: -r requirements.txt

      - name: Freeze dependencies to local path
        run: |
          mkdir -p ./python_packages/lib/site-packages
          python -m pip install --target=./python_packages/lib/site-packages -r requirements.txt

      - name: Zip deployment package (includes python_packages)
        run: |
          zip -r deploy.zip . -x "*.git*" ".github/*" "tests/*"

      - name: Deploy to Azure Functions via ZIP
        uses: Azure/functions-action@v1
        with:
          app-name: bookmarkgenie-functions
          package: deploy.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
