name: Deploy OutlierFinder to Azure Functions

on:
  push:
    paths:
      - 'OutlierFinder/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-outlierfinder.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4
    
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match Azure's host Python version
    
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: 🚀 Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: bookmarkgenie-functions
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
