name: Deploy DependencyTest to Azure Functions via Oryx

on:
  push:
    paths:
      - 'DependencyTest/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-dependencytest.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 📦 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 🔧 Build and deploy using Azure Oryx
      uses: Azure/functions-action@v1
      with:
        app-name: bookmarkgenie-functions
        package: './DependencyTest'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
