name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          cli-version: 'latest'

      - name: Deploy to Azure Web App using CLI
        run: |
          az webapp up \
            --name BookmarkGenieApp \
            --resource-group BookmarkGenieResources \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --plan BookmarkGenieAppPlan \
            --runtime "PYTHON:3.9"  # Specify your runtime here
